replicaCount: 2
revisionHistoryLimit: 1

image:
  repository: gcu-lucky7-dev.kr-central-2.kcr.dev/lucky7-cr/image-service
  tag: "2"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 9000

selector:
  app: image-service-pod

envSecretName: moaboa-env
imagePullSecretName: kc-lucky7-cr

canary:
  maxSurge: 1
  maxUnavailable: 0
  steps:
    - setWeight: 50
