apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: image-service-rollout
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      containers:
      - name: rollout-image
        envFrom:
        - configMapRef:
            name: image-service-config
        - secretRef:
            name: {{ .Values.sealedSecretName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
  strategy:
    canary:
      maxSurge: {{ .Values.canary.maxSurge }}
      maxUnavailable: {{ .Values.canary.maxUnavailable }}
      steps:
      {{- range .Values.canary.steps }}
      - setWeight: {{ .setWeight }}
      {{- end }}
