apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecretName }}
spec:
  encryptedData:
    image-vault-token: AgCN/8/p70AOdusJtDndouPmOYPXvjhbhXZ1D0skrApU3ibxe8C0r7RiUmV1N13DA398k6s11ZFjotNE+jHklUmz3jaOikX9RGMolAOdH7SgZ8w8F3+befOK13J2hFvBQ9WZj3i1tA6UOY2d/7a+lR2WjrXFgL+3ffefjZ9ZPDYExtniUUfja/abR/gxfTujUkjyhdcvIOvr8+j95diAy5r2VfEr7BZIYQrF4f9SWpcmFlZ3mnfqplnLHjJ22NUu8GvEVN5eG58xyo5Kex14VcPsCN6prvBeRWpXGzZ4DJ7rXqX4vF/pAdwje0SJM8E5+wgH0ZyHh06aCs2mw6iyePhF48q3mUIzyjnyodBfurvKs5UmZrTd251kFYlA9rEAl05xFa8mpqaWmV4ElTJXdMZj0474au0YClOw2Cq+wW8uBZVXHHixAF7DigCA1suGex74CNU0JiicYJ+d+qcDrITz35b60K1A51tggs5MI5SQueHOSKFRI2k/LocO+plfncIG5oJGETtKOcpQlCTp986Hr90E1ye98lS/GwuIw4+WJxYRN5UQSSLUfFDsHHoMMz26WR7beYuQVOcXIJtOLhKeV9vsLSlsEo0tfmHHFuvHcM2RFTvjDzRiNAkZCL2TzDu3HkCcGVMreKJlsGMkSqIfhXo5GARXQ5Mbk6Km9GoQH4mASdk1A+Jn7mTDberWXyOEk+Si9+xQDHvfk0RjvKZxa63fm87OJjXiTI4b692tQlZYJNc1UD2q3D6sW74n0ePTyRjNDSRSSSkjUO4gYA/UKi8huAgJ4lLiF6F3nYK73RCIG6fnoMG2FNiPcmvFxg==
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sealedSecretName }}
      namespace: moaboa