apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecretName }}
spec:
  encryptedData:
    image-vault-token: AgCGu63WwIi7RWcaAuKCkaNh4JmHzwMVWfiIeW56eD0TeaGdw/EdT5FSk7rllnUbz7hqpfepJWUCMczW5dQ8SUXPh+kq7bMvwzqZtPOWAJUklfrBTZeI9zmxmAx58GCj4vClrBeckgVXevYIRUdhhVBhbb2YTqLIKFuBmlB+y0F2GdF/dM0vOK6fG8mbAjNO4WATe/H7qTFByFaRacQQdPIAgjj0WROqu8L2/3IffbLdYdRr6UqEWaC4/w5yIBVdBl0+OEy7dA4I6CrN4HLs9NxmnGD+P7W8j5/28PJA+KjDYIU8isskD733fnDL01+yBHXIxkButZ1qhBCa3xTYBK3Xe37O/v6KvxJE3ojmlWR9tET+HFA/WN3QTOmLYSDwok7thfx8kKJBzje0lgnnZ6V3AwT/NZsAM1pwv/PqCAmf6D4woG5FB/+lC92x1UNZWCFugO/Az81ZZ83PDUKEkS3Yqa2uozQqcdi9FbmI3vzfuieDf9JQo5H6CH7o0kDsp/6/oKX6DGuGPsdOfG+ZymJlGAEHmhH99Ay5WYlHbTVwM1nQslFXTr7CPrVpJdIwtsfHPW6Imc7Kq/4Qg6CAL7QpZoiSa8c9jqcdxUHCh0kDGm4VtHXK3zfHeLU8P4B+O9dgtFMEKwJMV7I4ZQV5u7RhUuDGUL+xzK5/nlfpf318V7+rMMjyjkySsrP8prYyIV2ckLAaZeCXTel7DR6m2l3RJZGcT6rarOAmRggMo9xhent2IvkJMWcVbieU+aiQ8up0Gm1jJ1DiQtg8Hn2wW/tX9ZQgQiv6KkTrgjxfdg7Pk5OJz4XVRjokPyXK2/eC/A==
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sealedSecretName }}
      namespace: moaboa