replicaCount: 2
revisionHistoryLimit: 1

image:
  repository: gcu-lucky7-dev.kr-central-2.kcr.dev/lucky7-cr/report-service
  tag: 19
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 9000

selector:
  app: report-service-pod

envSecretName: moaboa-env
sealedSecretName: report-vault-token
imagePullSecretName: kc-lucky7-cr

canary:
  maxSurge: 1
  maxUnavailable: 0
  steps:
    - setWeight: 50
