apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecretName }}
  namespace: moaboa
spec:
  encryptedData:
    search-vault-token: AgCpFoPAoOmxWJ3JIM2o+tL4P54jy0Ws6TETeEbKZqj6SY1lNr7T6z0oU8DIbeApnFbId5jBq172Z3teO5EMOgMcAsEI3Ri5SE9RagFXKm8RWJiwSkzd5AqF1+td+ITsgkNaEMyC9sjYbapfSmQpXgdhIKn1L9teBlV7gc7zjTMrXEIzekc+2efmxQsFSoksz/KrGDS4I+JQ133Mm38uY9Ls+a69GjVjeW7hrL04jVcPJ/EaqGbRKYHe82xwbKeIu8ytQxz5LbQ8wGK4d8nXBkmkCPAD+xAWuKfBu+BrPOqVfT2DlALB4NVTyDdGWkTfSOMz7AWAuGYmbt9o9nCwIKk9cgXNJRYPXMkYnAQZ8OqPtq/sKH43RPGxN1pBsv3xbQmrcB0dUUIjdAEs1mSNFnLHy1lKCq+JfAfaC5qu5PBPs4KodHQ3UCU7W4kvKZZngY53nz1npFjG2jMqaToi1+fPrs7tNzbYM9wY/+3EDpO/G8nUqwcGYtpcy7oWqea7P8ketMA+ijViZzS+QKyj844KFUYD5kSm+yqTdNUz2IPyeWrhhAx1dVP8CuVm1Sfn5Ep5RJHqlyahY6ATbkGzKRqyPbioewjiws3oGQmUW/PfTDEZsmf4FLiI6ThpJmXSjKDAldHX1dsMN2UAYV9l8OyXqo6jksAMu+u/ru0jX/edwNOxWBC6eP/kqo+Nnq8zA+E27PaKNuW5uA8NeSHNVPgKCb88IR4pIDMgtPYZExbq/sCxgedt8+N0HJLNgdc2O70rqIpmU4yERk48mG6/IDkElU3862GHtSzpxl4cr+bf4wzCrEimnlNuMESTjjIvtw==
  template:
    metadata:
      creationTimestamp: null
      name: search-vault-token
      namespace: {{ .Values.sealedSecretName }}