apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecretName }}
spec:
  encryptedData:
    search-vault-token: AgBR9dFkALcD1qf+v2gKHnLRXcwFpdSQHY19ktI7tD7SUTaEryM6xUn5L61u2Hc+wxlEw6z2ZbElQ/8ksT32EIbktukXLqiUwt2fnZW7vnxrRMrd/Tg6mBL5slgNhogf4XhPtYp8BFbmv0en8tTjh6KEkeiMS5cYEdzJnmp1mJrn1FCLgCN6vkpaeHGD2E2qmQzvs19EI0W4YRH1nY5Kx2TN7cMkE7F0FaXPs3GRmMta/5MzAn+0RiYtaS4ilhM6asUbrLOMRYZ1oHeZonskxSvkAlXpemcZGsJyVpShj0c//Kt5eGc1SfuTTwna7qGRHHpNqBfZ+gBJUi0HbTuayRetyEkRhoOz6GnGzs0hSwsmZBfqPUtTTx6oGZzCgJX4RiNDN2909GGgrtPS+eH8klnYALc/38p2ReTOc5/iVYXFJAEMzDZpbljDU2UCIxx7N8aUXq5m4VDjrytkOdLGwcksSwA1hQ9qadvOZYNifl+8+iRlTtVpcFMa2QeYXjsCa86eU/NpzpThZhyzZCLte9MytHh3JvUBGV3TgQnmVULO0At3h/W8z5YtChnmBxzuIOTBvZ3v1Kjluk94BHeFDsuZsE+GZmwqUfhKXRXFRBNA58PNke+db5wEEJnYhX7HfxvlOfjJ3KOvPbBdEWzVpD3qZHpKXILOu7yF4WCyiCh3k2mrKSgYeo6gZWakLWAJo+z1XGQk1h6gr9Ff1hw3WUFO2YoO7uEVcDOnTHbc87kgJ992c+TKqx3q4mw18ZU1Je8tiiKdz5k9pGjNyc1mk1Oc6ck2/j1OlM7thVxIo6P2aLqTRQ2A9s0s1fsCucI8dw==
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sealedSecretName }}
      namespace: moaboa