apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: post-service
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/KEA-Lucky7/MOABOA-GitOps.git
    targetRevision: main
    path: charts/post-service
  
  destination:
    server: https://kubernetes.default.svc
    namespace: moaboa
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - 'CreateNamespace=true'