---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.sealedSecretName }}
spec:
  encryptedData:
    report-vault-token: AgAO4uCL0KmSbog0mXnlmkJ8Na0AqxC8Jjl4MIZ9xUZsOcG/ftymMcW/I4f4ok1EdQlKYt8pu3VcKEJiC5hETtEbrqmULsDVuho8wz0rPI3cG4UkG/aFqTfWE0mSD/k3lQLskXn23ejSeTZOqur9RcWrlw8qk0Tf7UWZaYqSTGDcOvKi7CDnr36DeznORlZM4VR7Se5MB6+q1fim+/uMW0b+VxRrkeOgdE+dBBQCggJi2kfV+ZEywAz5KpG8NQz7j/QOt4zIfq56ZW7Di8icZL6R4lEJpUG5GtnrF7egvSrKYX6b5OrvzK8WpgXy9s3uJSo3C9l6Bs5rsc/BuGUkhASYY6aYhQb9qDE6UofqOA9mI7PYMLNKKSpEUWsbikcQWAiAYVe6y2+cg8S7ugFVHuv1toIjavHouBjuDk/nDa0ye2Zd4+X0a8b+OWTZneYO7BScTAYQmfltDOMqs4f5qqmH9z5VuG7OjJ9ZfN4xqXfmYoIa+moaTKdE+Fhltaca4Mn4eZUfVsCqDVrCED8FASzKNudS7hLwAA7Xs/6eKNL8e/XCtbAabREqee7c29cqpBwV02MbHabYKznfFbZcaiXOz9b7TMmR+IauUwk9If9sFCiAksr1/oI7nf8qb/JJFyPotxSFO3a5RZygL4UzLjgyfSf1DYgnoveX4mT+KBAKucS54ABhE0fuZotmzAaihwzBS+MIGSlImCTiQXY+hENj4Grfp9UcsCwPS57Y0izkgX1FpO6u++vahFsIyxFLR7zsziKMTB2bdSZPa+E1Sl4ec8ilICDsBqOBV7ruOI8h9DDwkvFlqFsdEFZHl6IOLA==
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.sealedSecretName }}
      namespace: moaboa